// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $era_converter from "./routes/era-converter.tsx";
import * as $index from "./routes/index.tsx";
import * as $nippon_things_layout from "./routes/nippon-things/_layout.tsx";
import * as $nippon_things_about_the_blog from "./routes/nippon-things/about-the-blog.tsx";
import * as $nippon_things_categories from "./routes/nippon-things/categories.tsx";
import * as $nippon_things_category_category_ from "./routes/nippon-things/category/[category].tsx";
import * as $nippon_things_home from "./routes/nippon-things/home.tsx";
import * as $nippon_things_posts_post_ from "./routes/nippon-things/posts/[post].tsx";
import * as $contact_me from "./islands/contact-me.tsx";
import * as $converter_search from "./islands/converter-search.tsx";
import * as $info_box from "./islands/info-box.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/era-converter.tsx": $era_converter,
    "./routes/index.tsx": $index,
    "./routes/nippon-things/_layout.tsx": $nippon_things_layout,
    "./routes/nippon-things/about-the-blog.tsx": $nippon_things_about_the_blog,
    "./routes/nippon-things/categories.tsx": $nippon_things_categories,
    "./routes/nippon-things/category/[category].tsx":
      $nippon_things_category_category_,
    "./routes/nippon-things/home.tsx": $nippon_things_home,
    "./routes/nippon-things/posts/[post].tsx": $nippon_things_posts_post_,
  },
  islands: {
    "./islands/contact-me.tsx": $contact_me,
    "./islands/converter-search.tsx": $converter_search,
    "./islands/info-box.tsx": $info_box,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
