// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $blog_layout from "./routes/blog/_layout.tsx";
import * as $blog_home from "./routes/blog/home.tsx";
import * as $blog_posts_post_ from "./routes/blog/posts/[post].tsx";
import * as $era_converter from "./routes/era-converter.tsx";
import * as $index from "./routes/index.tsx";
import * as $converter_search from "./islands/converter-search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/blog/_layout.tsx": $blog_layout,
    "./routes/blog/home.tsx": $blog_home,
    "./routes/blog/posts/[post].tsx": $blog_posts_post_,
    "./routes/era-converter.tsx": $era_converter,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/converter-search.tsx": $converter_search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
